spring:
  application:
    name: api-gateway

server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
#          filters:
#          - StripPrefix=1
#      routes:
#      - id: auth-service
#        uri: lb://auth-service/
#        predicates:
#        - Path=/auth-service/**
#        filters:
#        - StripPrefix=1
#      - id: soccer-service
#        uri: lb://soccer-service/
#        predicates:
#          - Path=/soccer-service/**
#        filters:
#          - StripPrefix=1
